apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-deployment
  labels:
    app: spapp
spec:
  selector:
    matchLabels:
      app: spapp
  template:
    metadata:
      labels:
        app: spapp
    spec:
      containers:
        - name: sp-container
          image: alexspirin/automatingdeploy:latest
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sp-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sp-deployment
  minReplicas: 3
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sp-service
  labels:
    app: spapp
spec:
  type: LoadBalancer
  selector:
    app: spapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
